### ISSUE TITLE
Unexpected way of using sesskey

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-filter_gurls#3]
Using sesskey in a way like `required_param('sesskey', PARAM_ALPHA);` or checking against `$USER->sesskey` manually does not seem right. Your scripts should never (need to) do that.

Simply, you call `require_sesskey()` when checking for it and call `sesskey()` to obtain the current value to be put into forms and URLs.

Additionally, when using `moodleform` subclasses properly, the sesskey is checked automatically on data submission.

**Comment by mudrd8mz** [comment]
So I can see all sesskey checks were removed. I am afraid that was not the right step. At the moment, your code is vulnerable to [XSRF attacks](https://docs.moodle.org/dev/Security:Cross-site_request_forgery). For example via things like `<img src="/path/to/deletedefault.php?defaultid=1&confirm=1" />`

**Comment by ned-code** [comment]
Fixed in this commit: https://github.com/fernandooliveira/moodle-filter_gurls/commit/e4732ff34d10296ed35327f0d819b9ca6dcd56d7
