### ISSUE TITLE
Is gurls.js actually working in Moodle < 2.9 ?

### ISSUE THREAD

**Issue by mudrd8mz** [fernandooliveira/moodle-filter_gurls#4]
I am a bit surprised by the JS code in gurls.js. As I understood, the support for AMD modules and the `require()` syntax was added only in Moodle 2.9 - https://docs.moodle.org/dev/jQuery#With_a_require_call

For previous Moodle versions, https://docs.moodle.org/dev/jQuery_pre2.9 should apply

**Comment by mudrd8mz** [comment]
Any comment on this?

**Comment by ned-code** [comment]
gurl.js is used only for moodle 2.9
for M2.7 and M2.8 gurl.js is not used . Instead a separate page is used there after you click the edit button. So it won t be done inline, but with the help of a separate new page
